POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John" 
}

//POSTがリクエストできない、The connection was rejected. Either the requested service isn’t running on the requested server/port, the proxy settings in vscode are misconfigured, or a firewall is blocking requests. Details: RequestError: connect ECONNREFUSED 127.0.0.1:3000.
//調べたけどよくわからん、APIの内容をJSONに出力して、静的にインポートしろみたいな…